### ISSUE TITLE
Cannot install App

### ISSUE THREAD

**Issue by cutzenfriend** [wreiske/Rocket.Chat.App-Giphy#16]
I get this error everytime I try to install the giphy app...

Exception in callback of async function: TypeError: Cannot set property 'subscriptionInfo' of undefined     at AppManager.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:491:65)     at Generator.next (<anonymous>)     at /app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:7:71     at new Promise (<anonymous>)     at __awaiter (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:3:12)     at /app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:478:73     at Array.map (<anonymous>)     at AppManager.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:478:44)     at Generator.next (<anonymous>)     at /app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:7:71     at new Promise (<anonymous>)     at __awaiter (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:3:12)     at AppManager.updateAppsMarketplaceInfo (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:477:16)     at app/apps/server/orchestrator.js:155:24     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at _appsUpdateMarketplaceInfo (app/apps/server/cron.js:93:10)     at runWithEnvironment (packages/meteor.js:1286:24)     at packages/meteor.js:1299:14     at Object.job (app/apps/server/cron.js:104:3)     at packages/littledata_synced-cron.js:251:26     at scheduleTimeout (packages/littledata_synced-cron.js:304:9)     at packages/littledata_synced-cron.js:356:42     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by wreiske** [comment]
Are you installing it from the marketplace or manually? And which version of Rocket.Chat?

**Comment by cutzenfriend** [comment]
- Version : 3.2.2 
- Tried installing from Marketplace
- I'm using the Docker Container
